### PR TITLE
Worker objects no longer access global parameters

### PR DESCRIPTION
**Pull request by felixschorer**
Nothing major, it was just bothered me 😄

### CODE REVIEW

**Comment by gyachdav** [comment]
Hello G2. Nice progress over the last few days. When do you plan to start running your pipeline and generate the data for the relationships groups?

**Comment by felixschorer** [comment]
@gyachdav We ran it yesterday night for about half an hour when the DB simultaneously dropped all our DB connections. I just pushed a hotfix for that. #208 

5,3% of the files have been processed. Due to now having a global task queue we can pick up right where we've left yesterday.

**Comment by gyachdav** [comment]
So an entire rub should take 10 hours?

**Comment by felixschorer** [comment]
Yes, that's my estimate as well. Currently testing all changes in from the hotfix.

**Pull request merged**
