### PR TITLE
Switches language detection from franc to cld for performance reasons.

### PR DESCRIPTION
**Pull request by LukasS96**
Change seems to reduce time complexity by about 90%, further testing may be required.

Note that this implementation requires use of callbacks for language detection.

### CODE REVIEW

**Comment by anshul0708** [comment]
I was testing CLD as well. But cld is giving me no result for this page : http://109406.peta2.jp/?ts=1365043013&guid=ON


Therefore after this page it exits with an defined error. Is it running ok for you ?

**Comment by LukasS96** [comment]
Worked fine on my dataset. Only error I'm getting is "Failed to identify language" for some websites but that can easily be handled. Feel free to try out my code :)

**Comment by anshul0708** [comment]
Yeah, had a look at your code. I was extracting language from the chunks field, and that some times isn't generated.
CLD for me as well is running around 8 times faster than franc. We should be using this.

Could you remove TLD as an argument though, it can be easily extracted from the webpage class via getTLD(). Therefore I feel it is somewhat unnecessary as an argument.

**Comment by anshul0708** [comment]
If anyone on windows faces trouble running cld on windows, you can install 'npm install --global --production windows-build-tools'. Takes around 20 minutes.

**Comment by lgfrbcsgo** [comment]
This so much faster! Took me 8 seconds! Thanks for the hint with the build tools, @anshul0708

**Comment by sacdallago** [comment]
Guys you are great but don't forget to delete branches ones they are merged! 🚓 Also: not using multithreading up until now, right? I guess you are gonna split the data in threads, rather than the computational aspect?

**Comment by nyxathid** [comment]
Yes, so far we have been using one thread only. Future plans are:
- download an process data on the fly (no buffering on disk -> #33 )
- use multi threading 

BUT there is still a question: If with one thread we can process data *faster* than we can download it, does it even make sense to use multi threading? If the download speed is fast enough we can start multiple threads and assign a single WET file to each of them.

**Comment by sacdallago** [comment]
@nyxathid That's what I meant with dividing the data into threads. It makes more sense to me as well.

**Comment by lgfrbcsgo** [comment]
@nyxathid I was thinking about using staggered launch. We have one master thread which starts our processing chain (download -> unpack -> pre-process -> ...) in a new worker thread. Once the chain reaches the unpacking part it will notify the master to start the next worker thread. After a thread is finished it reports its results to the master. Getting the processing chain going doesn't require multi-threading, that's why we're still stuck with a single thread, @sacdallago.

**Comment by kordianbruck** [comment]
@sacdallago you are hijacking the PR for a discussion that is better kept in an issue - no one will find this here in a weeks time.

@topic: I would advise for a worker schema - that way you can dynamically add / remove more workers for each task and see that theres a balance between the two of them. There are several aspects here to be considered:
- Download speed of the connection link
- Upload of the server we are actually pulling from (might be limited per ip or something?)
- Size of the RAM / Cache / Disk
- Speed of the Database you are saving it to and the connection to it - it probably won't be local host
- Number of cores and their speed

This is inherently not something that we can pre compute and say: hey, 2 download threads and 8 consuming threads are ideal, but that needs to be balanced on the go. =>probably better discussed in an issue.

**Comment by sacdallago** [comment]
@kordianbruck do I get spanked for this? Asking for a friend...

But yeah, right :) This can become a feature in your backlog / an issue rather than just thin air :)

**Comment by kordianbruck** [comment]
@sacdallago I can do some good spanking any time :wave:

**Pull request merged**
