### PR TITLE
Report

### PR DESCRIPTION
**Pull request by nyxathid**
Almost final draft of the report. Compiled PDF for lazy ppl: [report.pdf](https://github.com/MusicConnectionMachine/UnstructuredData/files/962220/report.pdf)

Please take a look at it. **Especially** at the "Internal task distribution" section. Please add some words about what **you** did and how cool **you** are. I probably forgot half of your achievements ;)

If you find something to be improved, pull this branch and change the part yourself! I tried to be git-friendly: one sentence per line.

### CODE REVIEW

**Comment by felixschorer** [comment]
Looks good, but most of it is just headings... 😟 
Do we have to use that template? @nyxathid

**Comment by nyxathid** [comment]
We can use any template that looks good

**Comment by nyxathid** [comment]
Do we have to write stuff about our presentation (RESTful APIs)?

**Comment by felixschorer** [comment]
> Do we have to write stuff about our presentation (RESTful APIs)?

Thank god, no 😄 

I'd merge some of the paragraphs into a single larger one to get rid of the headings. Like "Internal task distribution", "Timeline" and "Problems and feedback" shouldn't have headings in them.

**Comment by nyxathid** [comment]
Here is the newer version with less headings: [report.pdf](https://github.com/MusicConnectionMachine/UnstructuredData/files/970345/report.pdf)
@felixschorer what other template would you prefer?

**Comment by felixschorer** [comment]
I don't think this belongs into the develop branch? Shouldn't this be merged into master?

**Comment by nyxathid** [comment]
Not yet, maybe Anshul or Lukas still want to change something. And we are going to merge develop into master anyway, right?

**Comment by felixschorer** [comment]
I don't think so. Master is only for tracking version numbers afaik.

**Comment by nyxathid** [comment]
Let's ask the tutors tomorrow during the final meeting ;)

**Comment by kordianbruck** [comment]
Develop will be fine - develop is the new master ;D

**Pull request merged**
