### PR TITLE
Terms will now be changed toLowerCase in webpage-digester

### PR DESCRIPTION
**Pull request by LukasS96**
- Terms will now be changed toLowerCase in webpage-digester before assigning them to filters.

- Removed changing terms to lower case in the filters.

- Fixed bug in storer where relations would not be properly stored.

### CODE REVIEW

**Comment by nyxathid** [comment]
True, we forgot about the input text/website content. @lgfrbcsgo you know that code better ;)

After additional changes, please merge `develop` into **this** branch! Otherwise the api submodule versioning will become a complete mess.

**Comment by lgfrbcsgo** [comment]
> After additional changes, please merge `develop` into **this** branch! Otherwise the api submodule versioning will become a complete mess.

Yes, sir.

**Comment by lgfrbcsgo** [comment]
@nyxathid Please have an other look at it. `Filter`s and `IndexFilter`s should be case sensitive now, `WebPageDigester` shouldn't be. I also wrote some tests to test that 😎

**Comment by nyxathid** [comment]
my tests were weird... but now everything is passing

**Pull request merged**
